exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Rakefile
  - README.md  

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

title: Ruby on Rails Indonesia
description: Framework aplikasi web yang mencakup semua yang diperlukan untuk membuat aplikasi web yang didukung database sesuai dengan pola Model-View-Controller (MVC).
image: https://avatars.githubusercontent.com/u/46654718
lang: id_ID
defaults:
  - scope:
      path: ""
    values:
      image: https://avatars.githubusercontent.com/u/46654718
